"use client";

import { AntdRegistry } from "@ant-design/nextjs-registry";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Flex } from "antd";
import Link from "next/link";

import "./globals.css";
import { css } from "@emotion/css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Flex
            gap={16}
            align="center"
            className={css`
              border-bottom: 1px solid #f0f0f0;
              background-color: #ffffff;
              padding: 20px;
            `}
          >
            <Link href="/">Dashboard</Link>
            <Link href="/charts">Charts</Link>
          </Flex>
          {children}
          <Toaster />
        </AntdRegistry>
      </body>
    </html>
  );
}
